config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :orders
  resources :carts
  devise_for :users 
  resources :formations
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord

    belongs_to :user
    has_many :line_items
  
    def cart_total
      sum = 0
      self.line_items.each do |line_item|
        if line_item.formation.price == nil
          line_item.formation.price = 1
        end
        sum+= line_item.formation.price
      end
      return sum
    end
    
    def self.current_cart_id
      self.all.find_by(user_id: current_user.id)
    end
  
    def destroy
      self.line_items.each do |line_item|
        line_item.destroy
      end
    end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  def index
    @carts = Cart.all
  end

  def show
    @cart = Cart.find_by(user_id: current_user)
  end

  def destroy
      @cart = Cart.find_by(user_id: current_user)
      line_items = LineItem.where(cart_id: @cart.id)
      line_items.each do |item|
        item.destroy
      end
      redirect_to formations_path
    end
  
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
 
<section>
<p id="notice"><%= notice %></p>
<br> <br> <br>
<h3>Votre panier</h3>
<section>
<table>
  <thead>
    <tr>
      <th>Cart ID</th>
      <th>User ID</th>
      <th>Formation</th>
      <th>Price</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.id %></td>
        <td><%= cart.user.id %></td>
        <td><%= cart.formation.title %></td>
        <td><%= cart.formation.price %></td>
</section>
<section>
        <td><%= link_to 'Show', formation_path(cart.formation.id) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'êtes-vous sûr de vouloir supprimer ce panier' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</section>
<br>

<p><strong>TOTAL PRICE : <%=@cart_total%></strong></p>
<br>



<%= link_to "Back", request.referer.present? ? request.referer : root_path %>
</section>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<section class="p-0 bg-orange">
  <div class="image image-overlay image-cover" style="background-image:url(../../assets/images/demo/coworking/coworking-small-13.jpg)"
      data-top-top="transform: translateY(0px);" 
      data-top-bottom="transform: translateY(-250px);"></div>
<div class="container">
  <div class="row justify-content-left align-items-end vh-30 mb-5">
    <div class="col col-md-10 col-lg-8">
      <div class="row align-items-center">
        <div class="col">
          <div class="row align-items-center">
            <div class="col-md-8">
            <h2 class="mb-0">Votre Panier</h2>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</section>

<section>
  <div class="container bg-light">
  <%if @cart.line_items == []%>
              <div class="text-center">Votre panier est vide, découvrez nos ateliers ... </div>
              <div class="text-center"><%= link_to "Nos ateliers numériques", formations_path, class: "btn btn-primary btn-sm"%></div>
            </div>
          <%else%>
            <table class="table">
              <thead>
                <tr class="font-weight-bold">
                  <th class="font-weight-bold" scope="col">Atelier</th>
                  <th class="font-weight-bold" scope="col">Prix</th>
                  <th class="font-weight-bold" scope="col">Action</th>
                </tr>
              </thead>
              <tbody>
                <% @cart.line_items.each do |line_item| %>
                  <tr>
                    <th scope="row"><%= line_item.formation.title %></th>
                    <td><%= number_to_currency(line_item.formation.price, unit: "€") %></td>
                    <td><%= link_to "Remove item", line_item_path(line_item), method: :delete %></td>
                  </tr>
                <% end %>
                <tr>
              <th scope="row"><%= link_to '<< Back to collection', formations_path %></th>
              <td class="font-weight-bold">Cart total:</td>
                            <td class="font-weight-bold"><%= number_to_currency(@cart.cart_total, unit: "€") %></td>
              <td><%= link_to "Checkout now >>", new_order_path, class: "btn btn-primary" %></td>

              </tr>
              </tbody>
            </table>

              



            <%end%>
</div>
</section>