config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :orders
  resources :carts
  devise_for :users 
  resources :formations
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/formation.rb
class Formation < ApplicationRecord
end

app/controllers/formations_controller.rb
class FormationsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_formation, only: [:show, :edit, :update, :destroy]
  

  # GET /formations
  # GET /formations.json
  def index
    @formations = Formation.all
    
  end

  # GET /formations/1
  # GET /formations/1.json
  def show
  end

  # GET /formations/new
  def new
    @formation = Formation.new
  end

  # GET /formations/1/edit
  def edit
  end


  # POST /formations
  # POST /formations.json
  def create
    @formation = Formation.new(formation_params)

    respond_to do |format|
      if @formation.save
        format.html { redirect_to @formation, notice: 'Formation was successfully created.' }
        format.json { render :show, status: :created, location: @formation }
      else
        format.html { render :new }
        format.json { render json: @formation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formations/1
  # PATCH/PUT /formations/1.json
  def update
    respond_to do |format|
      if @formation.update(formation_params)
        format.html { redirect_to @formation, notice: 'Formation was successfully updated.' }
        format.json { render :show, status: :ok, location: @formation }
      else
        format.html { render :edit }
        format.json { render json: @formation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formations/1
  # DELETE /formations/1.json
  def destroy
    @formation.destroy
    respond_to do |format|
      format.html { redirect_to formations_url, notice: 'Formation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_formation
      @formation = Formation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def formation_params
      params.fetch(:formation).permit( :title, :description, :price, :categorie, :session, :ref, :campus, :tag)
    end
end

app/helpers/formations_helper.rb
module FormationsHelper
end

app/views/formations/_form.html.erb
<%= form_with(model: formation, local: true) do |form| %>
  <% if formation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(formation.errors.count, "error") %> prohibited this formation from being saved:</h2>

      <ul>
      <% formation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/formations/edit.html.erb
<!-- hero -->
<section class="hero hero-with-header pattern bg-orange">
  <div class="image image-overlay image-zoom" style="background-image:linear-gradient( to right bottom,
            rgba(0, 0, 0, 0.3),
            #7f15db  )">
  </div>
  <div class="container ">
    <div class="row justify-content-center">
      <div class="col-md-8">
            
      </div>
    </div>
  </div>    
</section>
<!-- / hero -->


<h1>Editing Formation</h1>

<%= render 'form', formation: @formation %>

<%= link_to 'Show', @formation %> |
<%= link_to 'Back', formations_path %>


<div class="container">
<% content_for :title, "Edit formation" %>
<h1>Editing Formation</h1>

<%= form_with(model: @formation, local: true) do |form| %>
    <% if @formation.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(formation.errors.count, "error") %> prohibited this formation from being saved:</h2>
  
        <ul>
        <% formation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>
  
    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form-control" %>
    </div>
  
    <div class="field">
      <%= form.label :price %>
      <%= form.number_field :price, class: "form-control"%>
    </div>
  
    <div class="field">
      <%= form.label :categorie %>
      <%= form.text_field :categorie, class: "form-control" %>
    </div>
  
    <div class="field">
      <%= form.label :session %>
      <%= form.number_field :session, class: "form-control" %>
    </div>
  
    <div class="field">
      <%= form.label :ref %>
      <%= form.password_field :ref, class: "form-control" %>
    </div>

    <div class="field">
      <%= form.label :campus %>
      <%= form.text_field :campus, class: "form-control" %>
    </div>

    <div class="field">
      <%= form.label :place %>
      <%= form.text_field :place, class: "form-control" %>
    </div>

    <div class="field">
      <%= form.label :tag %>
      <%= form.text_field :tag, class: "form-control" %>
    </div>
  
    
  
  <div class="field">
  <%= form.label :image %>
  <%= form.file_field :image, class:"form-control mb-2 pb-2 " %>

  

</div>



<div class="actions mt-1">
      <%= form.submit %>
</div>

  <% end %>

<%= link_to "< Browse formation collection", formations_path, class: "btn btn-primary btn-sm mt-1"%>
</div>

app/views/formations/index.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- hero -->
<section class="hero hero-with-header pattern bg-orange">
  <div class="image image-overlay image-zoom" style="background-image:linear-gradient( to right bottom,
            rgba(0, 0, 0, 0.3),
            #7f15db  )">
  </div>
  <div class="container ">
    <div class="row justify-content-center">
      <div class="col-md-8">
            
      </div>
    </div>
  </div>    
</section>
<!-- / hero -->

<!-- formations -->

<section class="pt-0 pattern pattern-dark" align="center">
  
  <br><%= link_to 'New Formation', new_formation_path %><br/>
  
    <% @formations.each do |formation| %>
        
      <div class="item" onclick="location.href='<%= formation_path(formation.id) %>'", style="cursor: pointer;">
    
      <div class="image_formation image_item" style="background-color: rgba(255, 0, 0, 0.5) position: relative; z-index: 1;">
        <div class="space" style=" background-color:; position:absolute; z-index:-1; top:0; left:0; right:0; bottom:0; opacity:0.2; border-top-left-radius: 15px;
          border-top-right-radius: 15px;">
        </div>
          <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/barbarian.png" alt="img">
      </div>

      <div class="this-item" style="background-color: #108CB5; filter: grayscale(0.6);">
        <div class="titre_formation" ><%= formation.title %></div>
        <div class="description_formation"> <%= formation.description %> </div>
        <div class="prix_formation"> <%= formation.price %> € <br/></div>
        <td><%= link_to 'Destroy',formation, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-dark btn-sm mt-1"%></td>
      </div>

        <div class="categorie_formation clearfix" style="background-color: #108CB5;"> <%= formation.categorie %> </div><br/>
        </div>
        
</div> <!-- end item -->


  <style>

@import url(https://fonts.googleapis.com/css?family=Lato:400,700,900);

$border-radius-size: 14px;
$item: #EC9B3B;


*, *:before, *:after {
  box-sizing: border-box;
}

body {
  background : white;
  background-size: cover;
  font: 14px/20px "Lato", Arial, sans-serif;
  color: #9E9E9E;
}


.item:hover
{
  transform: scale(1.1);
  transition: all 0.3s;
}


.item 
{
  background: white;
  width: 300px;
  display: inline-block;
  border-radius: 20px;
  position: relative;
  text-align: center;
  box-shadow: -1px 15px 30px -12px black;
  z-index: 9999;
  color: white;
  margin: 15px 3%;
  min-height: 200px;
  margin-bottom: 20px; 
  
}

.image_formation 
{
  position: relative;
  height: 230px;
  margin-bottom: 18px;
  border-top-left-radius: 15px;
  border-top-right-radius: 15px;
}

.image_item 
{
  background: url('https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/barbarian-bg.jpg');
  img {
    width: 450px;
    position: relative;
  }
}

img
{
  width: 300px;
}

.titre_formation
{
  font-size: 20px;
  color: white;
  font-weight: 900;
  width: 100%;
  position: relative;
  top: auto;
    bottom: ;
    height: 70px;
    padding: 8px 5% !important;
    z-index: 2; 
    position: relative; 
    float: none;
}

.description_formation 
{
  color: white;
  width: 100%;  
  height: 80px;  
  padding: 8px 5% 50px;
    font-size: 14px;  
  line-height: 19px;  
  letter-spacing: 1px;  
  font-weight: 400;
  position: relative; 
  float: none; 
  
}

.prix_formation
{
  padding: 8px 5% 10px;
  color: white;
  font-weight: 600;
}

.categorie_formation
{ 
  color: white;
  font-weight: 700;
  font-size: 18px;
  text-align: center;
  border-bottom-left-radius: 15px;
  border-bottom-right-radius: 15px;
    position: absolute;
    width: 300px;
    position: absolute;    
    top:auto;
    left: 0px;
    bottom:auto;
    padding: 15px 26px 12px;
    border-radius: 0px 0px 20px 20px;
    
}


</style>

   

  <!--
        <h4 class="text-dark text-center"> <%= formation.title %> </h4>
        <p class="text-left"> <%= formation.tag %> </p>
        <p class="text-left"> <%= formation.categorie %> </p>
        <p class="text-left"> <%= formation.description %> </p>
        <p class="text-right"> <%= formation.campus %> </p>
        <p class="text-orange text-left"> <%= formation.price %> </p>
        <p> <%= formation.place %> place(s) dispnible(s) </p>
-->       


<!--
        <tr>
        <td><%= link_to 'Show me', formation_path(formation.id), class: "btn btn-outline-dark btn-sm mt-1"%></td>
        <td><%= link_to 'Edit', edit_formation_path(formation.id), class: "btn btn-outline-dark btn-sm mt-1"%></td>
        <td><%= link_to 'Destroy',formation, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-dark btn-sm mt-1"%></td>
        <td><%= link_to 'Add to cart', new_line_item_path(formation.id), class: "btn btn-outline-success btn-sm mt-1"%></td>
 -->       
      </tr>
      </div>
      <% end %>
    </div>
  </div>
</section>
<!-- / formations -->



<p id="notice"><%= notice %></p>

app/views/formations/new.html.erb
<h1>New Formation</h1>

<%= render 'form', formation: @formation %>

<%= link_to 'Back', formations_path %>


<div class="container">
<div class="row d-flex justify-content-center">
  <div class="col-md-6">
    <div class="accordion-group accordion-group-highlight" data-accordion-group>
      <div class="accordion" data-accordion data-aos-anchor-placement="bottom-bottom">
        <div class="" data-control>
          <div class="text-center">
          <button type="button" class="btn btn-primary mb-3">  Add my new formation </button>
          </div>
        </div>
          <div class="accordion-content" data-content>
            <div class="tab-pane show active" id="component-2-1" role="tabpanel" aria-labelledby="component-2-1">
              <div class="">
                <div class="container">
                  <div class="row">
                    <div class="col-md-12">
                      <div class="accordion-group accordion-group-steps" data-accordion-group>

                        <div class="accordion open" data-accordion>
                          <div class="accordion-control" data-control>
                          <%= form_with(model: @formation, local: true) do |form| %>
                          <h5>Upload pictures of your formation</h5>
                            <div class="field">
                            <%= form.file_field :image %>
                            </div>
                            <div class="accordion-content" data-content>
                              <div class="accordion-content-wrapper">
                              <% if @formation.errors.any? %>
                                <div id="error_explanation">
                                <h2><%= pluralize(formation.errors.count, "error") %> prohibited this formation from being saved:</h2>
                                <ul>
                                <% @formation.errors.full_messages.each do |message| %>
                                <li><%= message %></li>
                                <% end %>
                                </ul>
                              </div>
                              <% end %>
                              <div class="field">
                                
                                </div>
                              </div>
                          </div>
                        </div>
                      </div>

                        <div class="accordion open" data-accordion>
                          <div class="accordion-control" data-control>
                          <h5>Choose a good name</h5>
                          </div>
                          <div class="accordion-content" data-content style="max-height: 150px">
                            <div class="accordion-content-wrapper">
                              <div class="field">
                              <%= form.label :title %>
                              <%= form.text_field :title, class: "form-control" %>
                              </div>
                              <div class="field">
                              <%= form.label :description %>
                              <%= form.text_area :description, class: "form-control" %>
                              </div>
                              <div class="field">
                              <%= form.label :categorie %>
                              <%= form.text_field :categorie, class: "form-control" %>
                              </div>
                              <div class="field">
                              <%= form.label :tag %>
                              <%= form.text_field :tag, class: "form-control" %>
                              </div>
                            </div>
                          </div>
                        </div>
                        
                          <div class="accordion open" data-accordion>
                            <div class="accordion-control" data-control>
                            <h5>How big is your talent ?</h5>
                            </div>
                            <div class="accordion-content" data-content>
                              <div class="accordion-content-wrapper">
                                <div class="field">
                                <%= form.label :price %>
                                <%= form.number_field :price, class: "form-control" %>
                                </div>
                                <div class="field">
                                <%= form.label :place %>
                                <%= form.number_field :place, class: "form-control" %>
                                </div>
                                <div class="field">
                                <%= form.label :session %>
                                <%= form.number_field :session, class: "form-control" %>
                                </div>
                                <div class="actions">
                                <%= form.submit "Save my formation", class: "btn btn-primary mt-2 ml-10" %>
                                </div>
                              </div>
                            </div>
                          </div>

                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="accordion-content-wrapper">
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>
<% end %>

app/views/formations/show.html.erb
<!-- hero -->
<section class="hero hero-with-header pattern bg-orange">
  <div class="image image-overlay image-zoom" style="background-image:linear-gradient( to right bottom,
            rgba(0, 0, 0, 0.3),
            #7f15db  )">
  </div>
  <div class="container ">
    <div class="row justify-content-center">
      <div class="col-md-8">
            
      </div>
    </div>
  </div>    
</section>
<!-- / hero -->




<section class="bg-purple">

      <div class="container-fluid">
        <div class="row" data-aos="zoom-in">
          <div class="col">
            <div class="boxed p-5 p-lg-10">
              <div class="container">
                <div class="row justify-content-between align-items-center">
                




        <div class="container ">
          <div class="row">
            <div class="col-md-4 text-center">
              <i class="svg-icon fs-50 mb-1 ">
                
              </i>
              <h3 class="text-uppercase font-weight-normal fs-18 mt-2">Unique & Exclusive</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque velit dignissimos id repellat, consectetur dicta fugit</p>
            </div>
            <div class="col-md-4 text-center">
              <i class="svg-icon fs-50 mb-1 ">
                
              </i>
              <h3 class="text-uppercase font-weight-normal fs-18 mt-2">Carefully Crafted</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque velit dignissimos id repellat, consectetur dicta fugit</p>
            </div>
            <div class="col-md-4">
            <h2 class="h1">Find the right <br><b>room</b> for you.</h2>
            
<ul class="list-group list-group-line">
              <li class="list-group-item d-flex align-items-center">
                <i class="icon-briefcase2 fs-24 text-orange"></i>
                <span>Type d'atelier : hebdomadaire.</span>
                
              <li class="list-group-item d-flex align-items-center">
                <i class="icon-book2 fs-24 text-orange"></i>
                <span>Classes : CE1, CE2, CM1, CM2</span>
              </li>
              <li class="list-group-item d-flex align-items-center">
                <i class="icon-check-circle2 fs-24 text-orange"></i>
                <span>Session : du 22 janvier au 24 juin</span>
              </li>
              <li class="list-group-item d-flex align-items-center">
                <i class="far fa-credit-card fs-24 text-orange"></i>
                <span>Tarif : 250 € / session</span>
              </li>
              <li class="list-group-item d-flex align-items-center">
                <i class="icon-book2 fs-24 text-orange"></i>
                <span>Horaires : Mercredi 14h00 - 15h30 </span>
              </li>
              <li class="list-group-item d-flex align-items-center">
                <i class="icon-check-circle2 fs-24 text-orange"></i>
                <span>Lieu : campus de Pontoise</span>
              </li>
              
              <li class="list-group-item d-flex align-items-center">
                <i class="icon-check-circle2 fs-24 text-orange"></i>
                <span>Fast check-in included</span>
              </li>
            </ul>

            <button type="button" class="btn btn-with-ico btn-orange text-white mt-3">Make a Reservation <i class="icon-arrow-right2 fs-20"></i></button>
          </div>
          </div>
        </div>
      </div>


<br>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
<br><br>
<section>